### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by Richdark** [selfthinker/dokuwiki_plugin_abc#18]
First of all, thank you for developing this plugin, it allowed me to use my wiki the way I didn't hope for. Unfortunately, it didn't work for me out-of-the-box. I've never developed a DokuWiki plugin before, so it took me some time to figure it out, but finally I discovered that the problem is PHP version-related. The plugin uses `preg_match` with `/e` modifier for extracting ID and title needed to generate image name, but `/e` modifier has been deprecated since PHP 5.5 and removed in 7.0. Failing to extract these pieces of information, the resulting image name is broken and so is the rendered HTML.

The solution seems to be pretty simple - remove `/e` modifier. With this little change it works flawlessly for my version of PHP (7.3) and from what I read, the modifier is completely meaningless in `preg_match` function anyway, so it should be compatible with older versions as well. I can create a pull request if there is anybody who can review it and eventually merge too.

**Comment by selfthinker** [comment]
Thanks for letting me know. Sorry, a little late, but I have just fixed it.

**Comment by Richdark** [comment]
> Thanks for letting me know. Sorry, a little late, but I have just fixed it.

Glad to help, thank you as well!
